# Introducción a  Numpy

## Es una libreria de Python utilizada para trabajar con arrays.

In [4]:
import numpy

## Convertir una lista a array numpy

In [16]:
#x = numpy.array( [[1,2],[5,6]], numpy.int32 ) 
x = numpy.array(['hola','hola',1])
x


array(['hola', 'hola', '1'], dtype='<U21')

## Metodos

In [2]:
##dimenxiones fila x columna

In [17]:
x.shape

(3,)

In [ ]:
## tipo de dato

In [5]:
x.dtype

dtype('<U4')

## Extracción de elementos.

In [0]:
x = numpy.array( [[1,2.0,3],[4,5,6]] ) 

In [0]:
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
x[0,:2]

array([1., 2.])

## Trabajar con una copia

In [0]:
y=x[:,1].copy()

In [11]:
print(y)

[2. 5.]


In [0]:
y[0]=20

In [13]:
y

array([20.,  5.])

In [33]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
x[0:2,1:2]

array([[2.],
       [5.]])

## Conversiones de tipo de datos

In [28]:
x = numpy.array( [1,2,3,4,5,6,7,8,9], dtype=int )
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
m1 = x.astype( float )
print(m1)
print(m1.dtype)
print(m1.shape)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
(9,)


### Forma

In [30]:
m2 = m1.reshape( 3, 3 ).copy()
print(m2)
m2.dtype
print(m2.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)


In [19]:
m2[1,1] = -999
print( m1 )
print( m2 )

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[   1.    2.    3.]
 [   4. -999.    6.]
 [   7.    8.    9.]]


In [37]:
m3=m2.ravel() # desde n-D hasta 1-D
print( m3 )

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
m3[4]=5
print(m2)
print(m3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
